name: Execute APV

on:
  workflow_dispatch:
    inputs:
      device:
        description: Device to test (e.g. sunfish)
        default: sunfish
        required: true
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install python2 dependencies
      run: pip2 install --user protobuf

    - name: Install python3 dependencies
      run: sudo apt-get -y install python3-setuptools && pip3 install --user pyyaml gitpython

    - name: Run android-prepare-vendor for ${{ github.event.inputs.device }}
      run: python3 execute_apv.py -d ${{ github.event.inputs.device }}

    - name: Git diff
      run: git diff

    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Automated update of vendor_google_devices for ${{ github.event.inputs.device }}
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        title: 'Automated update of vendor_google_devices for ${{ github.event.inputs.device }}'
        labels: |
          automated pr
        assignees: dan-v
        reviewers: dan-v
        draft: false

    - name: Check output
      run: echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
